### ISSUE TITLE
Seeking feedback: QEP 179, Turning Plugin Management into Actual Package Management

### ISSUE THREAD

**Issue by s-m-e** [conda-forge/qgis-feedstock#125]
I hope this is the right place to ask - my apologies if it is not: I am currently running a [QGIS Enhancement Proposal (QEP) for turning plugin management into actual package management](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/179). As part of this process, I am looking for projects within the QGIS ecosystem which could significantly benefit from the proposed ideas and concepts. Because my QEP heavily references `conda`, the QGIS conda-forge package projects feels like a natural candidate.

In a nutshell, I am proposing to allow to package QGIS plugins as regular Python wheels and/or `conda` packages - with all relevant packaging features such as proper Python package dependencies and binary extensions. As a "side effect", this work could be the foundation for advanced tool-chains and deployment solutions based on `conda` / conda-forge and QGIS. If you find this work interesting and potentially relevant for this project, I am rather curious about your opinion. Among other issues, there appears to be some serious doubt about the existence of actual use cases for the proposed changes in QGIS among its core developers. Besides, the proposed work may also "confuse (plugin) developers". Feedback is therefore highly welcome.

**Comment by ocefpaf** [comment]
This is the right place and thanks for bringing this up!

My opinion strictly as a packager I have to say that this is an awesome idea! However, I'm not a heavy QGIS user to comment if this makes sense for them.

What I can say is: if you aim for PyPI/wheels we should be good on the conda side. There is nothing conda specific that would prevent us to just use the published PyPI package here. In fact, it would be easier b/c we can specify non-python dependencies easier them PyPI.

**Comment by SrNetoChan** [comment]
@s-m-e if you don't mind, I am closing this down. Please open it up again if you think it makes sense.
