### ISSUE TITLE
Master is failing on Windows after #137 was merged

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/qgis-feedstock#139]
Thw error us:

```
cmd.exe /C "cd /D %SRC_DIR%\build\python\plugins\db_manager && %PREFIX%\Library\bin\pyrcc5.bat -o C:/bld/qgis_1597842114271/work/build/python/plugins/db_manager/resources_rc.py C:/bld/qgis_1597842114271/work/python/plugins/db_manager/resources.qrc"
%BUILD_PREFIX%\python.exe: Error while finding module specification for 'PyQt5.pyrcc_main' (ModuleNotFoundError: No module named 'PyQt5')
[4283/4322] Generating gui/sip_guipart0.cpp, gui/sip_guipart1.cpp, gui/sip_guipart2.cpp, gui/sip_guipart3.cpp, gui/sip_guipart4.cpp, gui/sip_guipart5.cpp
```

We need to check what change from the time it was merged to the time this run again to figure what the reason for the failure.

**Comment by ocefpaf** [comment]
The only striking different is that the passing build had `conda-build-3.19.2-py36h9f0ad1d_3` and the failing one used `conda-build-3.19.2-py36h9f0ad1d_4`. @isuruf are you aware of any changes in that build number 4 that could have caused this?

**Comment by SrNetoChan** [comment]
OSX with python 3.8 also constantly hit the 6 hours time out. I was also working fine when it was merged.

**Comment by ocefpaf** [comment]
@SrNetoChan sorry but I lost track of this. Was it resolved or do we need to restart some jobs?

**Comment by SrNetoChan** [comment]
I lost track as well. I will have a look and let you know.

**Comment by SrNetoChan** [comment]
It seems that it was possible to build 3.14.16 so I guess whatever was going on is now fixed. Closing
