### ISSUE TITLE
qgis hangs in fresh install on fresh environment.

### ISSUE THREAD

**Issue by spittssj** [conda-forge/qgis-feedstock#168]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
QGIS hangs on startup in a fresh environment on Mac OS X Big Sur. Initially I tried to put it in an existing environment, but that didn't work, so I tried a fresh environment, and it still doesn't work. 

The installers on https://www.qgis.org/en/site/ work fine, but I wanted to programmatically use QGIS, so I am trying to install it in an environment I have created for my project. On the dock a QGIS icon pops up, but the main window never comes up. 

<pre><code>
stephenpitts@Ellacuria ~ % mamba create -n qgis qgis
< ... mamba output omitted ... >
stephenpitts@Ellacuria ~ % conda activate qgis
(qgis) stephenpitts@Ellacuria ~ % qgis
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
< ... just hangs here forever ... >
</code></pre>
<br/>
Environment (<code>conda list</code>):
<details>
<pre>
<code>
# packages in environment at /Users/stephenpitts/miniconda3/envs/qgis:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.72.0               hd067f63_4    conda-forge
brotlipy                  0.7.0           py39hcbf5805_1001    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2021.1.19            hecd8cb5_0  
cairo                     1.16.0            h4ec454a_1007    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cffi                      1.14.4           py39h7786acb_1    conda-forge
cfitsio                   3.470                hdf94aef_7    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
coverage                  5.4              py39hcbf5805_0    conda-forge
cryptography              3.3.1            py39h79a2c39_1    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
dbus                      1.13.18              h18a8e69_0  
exiv2                     0.27.1               ha4feea6_0    conda-forge
expat                     2.2.10               h1c7c35f_0    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h9ed2024_0  
future                    0.18.2           py39h6e9494a_3    conda-forge
gdal                      3.2.1            py39heec4134_2    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hc1004f4_3    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.66.5               h89d5895_2    conda-forge
glib-tools                2.66.5               h89d5895_2    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_h34ad4e8_1111    conda-forge
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
kealib                    1.4.14               h82515a5_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.0.1          default_hf8bb9ca_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         hed1e85f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgdal                   3.2.1                h1f7cb0a_2    conda-forge
libgfortran               4.0.0           7_5_0_h1a10cd1_17    conda-forge
libgfortran4              7.5.0               h1a10cd1_17    conda-forge
libglib                   2.66.5               h432db46_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h88bc94a_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.0.1               h223d4b2_0    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
libpng                    1.6.37               hb0a8c7a_2    conda-forge
libpq                     12.3                 h7049927_3    conda-forge
libprotobuf               3.14.0               hfd3ada9_0    conda-forge
libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
libspatialite             5.0.0                hc85de81_0    conda-forge
libssh2                   1.9.0                h39bdce6_5    conda-forge
libtasn1                  4.14                 h01d97ff_0    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp                   1.2.0                h1648767_0    conda-forge
libwebp-base              1.2.0                hbcf498f_0    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
libzip                    1.7.3                hccd5f62_0    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                1.1.1            py39hcbf5805_3    conda-forge
mock                      4.0.3            py39h6e9494a_1    conda-forge
mysql-common              8.0.22               h694c41f_3    conda-forge
mysql-libs                8.0.22               h70aab77_3    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nose2                     0.9.2                      py_0    conda-forge
nspr                      4.29                 hbc8d48c_1    conda-forge
nss                       3.47                 hcec2283_0    conda-forge
numpy                     1.20.0           py39h3c955ea_0    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
owslib                    0.22.0             pyhd8ed1ab_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
poppler                   0.89.0               hd735947_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 he852019_3    conda-forge
proj                      7.1.1                h45baca5_3    conda-forge
psycopg2                  2.8.6            py39ha9910ca_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyproj                    2.6.1.post1      py39hd525a1d_3    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt-impl                 5.12.3           py39hef7122c_7    conda-forge
pyqt5-sip                 4.19.18          py39hd8f94c5_7    conda-forge
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyqtwebkit                5.212            py39hd2546b8_1    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
python                    3.9.1           h2502468_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39hcbf5805_0    conda-forge
qca                       2.2.1                hc763db3_3    conda-forge
qgis                      3.16.3           py39he89333b_5    conda-forge
qjson                     0.9.0             hc763db3_1006    conda-forge
qscintilla2               2.11.2           py39h00c7726_4    conda-forge
qt                        5.12.9               h126340a_2    conda-forge
qtkeychain                0.12.0               h1456de6_0    conda-forge
qtlocation                5.12.9               hb1e8313_0    conda-forge
qtserialport              5.9.8                hc763db3_1    conda-forge
qtwebkit                  5.212                h0d65ee6_1    conda-forge
qwt                       6.1.5                h2815f34_0    conda-forge
qwtpolar                  1.1.1                h2815f34_7    conda-forge
readline                  8.1                  h9ed2024_0  
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                52.0.0           py39hecd8cb5_0  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tiledb                    2.2.3                h66dfca1_0    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
tzcode                    2021a                h35c211d_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xerces-c                  3.2.3                hd3a8c1e_2    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge
</code>
</pre>
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
<pre>
<code>
     active environment : qgis
    active env location : /Users/stephenpitts/miniconda3/envs/qgis
            shell level : 1
       user config file : /Users/stephenpitts/.condarc
 populated config files : /Users/stephenpitts/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/stephenpitts/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/stephenpitts/miniconda3/pkgs
                          /Users/stephenpitts/.conda/pkgs
       envs directories : /Users/stephenpitts/miniconda3/envs
                          /Users/stephenpitts/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
</code>
</pre>
</details>

**Comment by gillins** [comment]
Hi @spittssj can you try `export QT_MAC_WANTS_LAYER=1` before running `qgis` and see if that helps? I think this is a known problem with the version of Qt that conda-forge provides and Big Sur (see https://github.com/conda-forge/qgis-feedstock/pull/154#issuecomment-751894570 and https://github.com/conda-forge/qgis-feedstock/issues/89#issuecomment-765043628). 

Basically it is going to be fixed in the next point release of Qt 5.12.x (what conda-forge provides), but it isn't clear what to do in the meantime. I suspect this is a problem for all Qt apps on conda-forge and Big Sur. ping @conda-forge/qt

**Comment by spittssj** [comment]
Yes that fixed it: both in the new virtual environment <code>qgis</code> as well as my project virtual environment <code>comonsit</code>. 

<pre><code>
(comonsit) stephenpitts@Ellacuria Code % export QT_MAC_WANTS_LAYER=1 
(comonsit) stephenpitts@Ellacuria Code % qgis                        
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
<...QGIS window appears...>
</code></pre>

The Python console in QGIS is linked to the Conda virtual environment and so now I can continue with my task: batch processing some shape files and programmatically inserting them into our PostGIS database. 

Thanks for your help.
