### ISSUE TITLE
QGIS 3.0 release planning

### ISSUE THREAD

**Issue by ceholden** [conda-forge/qgis-feedstock#17]
QGIS 3.0 is scheduled to bring us Python 3 and Qt5 later this year. This issue is to get started keeping track of work needed to get us there.

Some dates from [their release schedule roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule):

* 2017-09-15: QGIS 2.99 feature freeze
* 2017-11-24: QGIS 3.0 release

@gillins has already started on Qt5 builds for QGIS's dependencies

* [x] qca
* [x] qwt
* [x] qwtpolar
* [x] qjson
* [x] QScintilla2
* [x] Qtkeychain
* [x] qt-location (submodule that isn't built with Qt)
* [x] libzip

With the release of 3.0, the current 2.18.x branch is slated to be the Long Term Release version, which might be worth maintaining if feasible because Python 3 and Qt5 will likely break many users' plugins. The 3.0 release also seems a good time to add builds for Mac and Windows.

cc @gillins @ocefpaf

**Comment by ocefpaf** [comment]
> With the release of 3.0, the current 2.18.x branch is slated to be the Long Term Release version, which might be worth maintaining if feasible because Python 3 and Qt5 will likely break many users' plugins.

I am creating a branch with the current state right now. So you can update to the latest version as soon as you are ready to do it.

**Comment by gillins** [comment]
`qscintilla2` PR here: https://github.com/conda-forge/qscintilla2-feedstock/pull/10

**Comment by gillins** [comment]
`qscintilla2` done and `qjson` PR here: https://github.com/conda-forge/qjson-feedstock/pull/6

**Comment by gillins** [comment]
`qtkeychain` PR here: https://github.com/conda-forge/staged-recipes/pull/3769

**Comment by gillins** [comment]
So seems we are ready for `qgis` 3? I suppose we need to wait for an alpha release of `qgis` 3 we can start testing a build...

**Comment by gillins** [comment]
@ceholden any news on when there might be a `qgis` 3 alpha we can start to play with?

**Comment by ceholden** [comment]
@gillins looks like the roadmap has been updated since the original post. The [updated post](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) puts the feature freeze for 2.99 (the 3.0 development build) in at Oct 27th, with the full 3.0.0 release slated for Dec 8th.

I haven't been able to find the time to test building the development branch seriously, but I'm hoping to get to it in the next week or two. I just did a quick test against the current HEAD of the QGIS repo on Github, and have found a few remaining dependencies, `libzip` and `qt5-location`[1], both of which seem pretty easy to build by themselves, although I think `qt5-location` has a dependency or two of its own (`qt5-declarative`[2] and `geoclue`[3]).

Hopefully that's it! I can probably get around to the deps and the build in the next few weeks

[1] `qtlocation` sometimes referred to as `qt-positioning` by package managers. Both modules come together. Sources include [the qt Github repo](https://github.com/qt/qtlocation) or from https://code.qt.io/qt/qtlocation.git
[2] https://code.qt.io/qt/qtdeclarative.git
[3] Geoclue is Linux only and releases are https://www.freedesktop.org/software/geoclue/releases/2.4/

**Comment by lpinner** [comment]
FYI - QGIS 3.0 release is now planned for [Feb 23](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and from chatter on the qgis-dev mailing list, I think that's a firm date this time.  

I've been running QGIS 2.99dev (what will be 3.0) on Win (via OSGeo4W) and Linux (via the QGIS nightly repo) for a while.

Happy to help testing a conda-forge build on Win/Linux (Ubuntu & CentOS) if that's of any assistance?

**Comment by ceholden** [comment]
@lpinner Thank you for the update on the release schedule and your offer to be a guinea pig! I've been seeing great things from the developer blogs and this will be my last need for Python 2, so I'm wicked excited that it's getting close to release. I haven't figured out the details of how to do this, but there are now development channels (`conda-forge/label/dev`) that we could use to test releases. I'm pretty clueless when it comes to Windows, but @gillins and others have added Windows builds for QGIS's myriad dependencies so it might not be too hard to get QGIS built for Windows as well. I don't happen to have a usable Windows VM at the moment 😬, so another set of hands would be great when the time comes.

As far as the Linux build goes, I found a few hours today to create recipes for the remaining dependencies (`qtlocation` and `libzip`), and I even got QGIS@master to compile successfully. Linux builds from my laptop for `qtlocation` and `libzip` are on my Anaconda channel (ceholden) to help test, but I should have the recipes for the dependencies submitted tomorrow.

There's some sort of issue that's preventing the QGIS 2.99 recipe from even starting its tests (my guess is that I still had `dateutil` listed, which is Py<=3.4, while conda-forge's version should be `python-dateutil`), but I'm hoping to figure that out later tonight or tomorrow. Anyway while I'm sure there's still surprises to come at me it was much easier to get compiled than I expected 🎉

**Comment by ceholden** [comment]
I said there'd be a surprise ahead of me, and I was technically correct. When I launched QGIS 2.99 for the first time, all the menus were blank! Luckily, this was just an issue related to the "look and feel" setting which relied on GTK+. This build doesn't know about GTK so it understandably was an issue, and switching to either "Fusion" or "Windows" style and restarting solved the issue.

Otherwise what I've tested seems to have worked. The Semi-Automated Classification Plugin seems to work fine (once I installed scipy and matplotlib), and to celebrate here's a screenshot of a WMS layer from NASA loaded with another map of the QGIS developers in the foreground.

![qgis3_map_in_the_map](https://user-images.githubusercontent.com/3585769/36220818-fa0806cc-1189-11e8-8c0f-d93204e8e4ba.png)

**Comment by gillins** [comment]
Well done @ceholden! I'm still keen to help with Windows and OSX but unfortunately I won't be able to do anything for the next ~3 weeks but will have a look when I can - if someone hasn't already beaten me to it.

**Comment by lpinner** [comment]
@ceholden I didn't realise you had a QGIS build in your ceholden conda channel.  Testing now.  The conda env creation went smoothly and the plugin I've been developing against 2.99 and 3.0 from the qgis.org/debian* repos seems to be working fine.

![image](https://user-images.githubusercontent.com/4827816/37180705-1be6c1c4-237e-11e8-80e4-d20eca259461.png)

**Comment by lpinner** [comment]
@ceholden I get the following error on CentOS 6.9 + conda 4.4.10 with your build. Did you build using your system compiler?

```(qgis-test) $ qgis
qgis: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by qgis)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by qgis)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by qgis)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../lib/libqgis_app.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ../lib/libqgis_gui.so.2.99.0)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../lib/libqgis_gui.so.2.99.0)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../lib/libqgis_analysis.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libqgis_analysis.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ../lib/libqgis_analysis.so.2.99.0)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by ../lib/libqgis_core.so.2.99.0)
qgis: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ../lib/libQt5WebKit.so.5)
qgis: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ../lib/libQt5Positioning.so.5)
```
I can get rid of the `libstdc++.so.6` errors by `conda install libstdcxx-ng` but that doesn't get rid of the `libc.so.6` errors.

**Comment by ceholden** [comment]
@lpinner sorry for the trouble -- those builds are indeed from my own system, but I should have time to upload new ones using the conda-forge Docker build today. I have to check back in on the recipe for `qtlocation`, but `libzip` is now a feedstock.

**Comment by lpinner** [comment]
@ceholden No trouble, I knew they weren't ready for general use, just thought I'd give it a go and pass on some feedback.

**Comment by ceholden** [comment]
I was hoping to get some new builds up for QGIS last Friday but I ran into a very tricky problem doing things correctly with the conda-forge Docker image instead of prototyping things on my local Arch install. I'm getting a few issues with the compiler not being able to find the appropriate signature to match functions up to inside of "new style" Qt signal/slot connect/disconnect statements using C++11 features (see build failures [here](https://gist.github.com/ceholden/b6179d58e17f983ce6f29b32531bb4fa)).

There's a few general hits out there on the internet, and someone from the QGIS mailing lists is having the same issue on openSUSE Leap 43, so I think it's probably a compiler bug that is affecting the combination of `gcc=4.8.*` and `qt=5.6`. I didn't hit the issue locally using my local gcc 7.2 and the CI builds of QGIS's repo uses `gcc=4.8`, but with `qt=5.10`. This isn't as good confirmation as finding an entry in a changelog, but I'm pretty convinced this is the issue.

I patched a few of the files that trigger this issue with a workaround and got through the compile step, only to have many other files others come up. I could keep going with the patching, and pray the thing links and works in practice, but I think the better solution is to upgrade the compiler. I looked into what's going on with the new compilers from Anaconda 5 (e.g., `gcc_linux-64` for `gcc=7.2`) and a few of the related elements at play (like upgrading to conda-build 3) but haven't made much headway otherwise. As far as I can tell, they're not ready to use yet. The QGIS devs test with Clang, and while I haven't done a full test run, I don't hit the error I encounter under gcc when using clang (from `clangdev`) so that's my next thing to explore.

**Comment by gillins** [comment]
> I think it's probably a compiler bug that is affecting the combination of gcc=4.8.5 and qt=5.6

:fearful: that is very unfortunate...

**Comment by ceholden** [comment]
@gillins It feels like I jinxed myself saying, "I'm sure there's still surprises to come at me"...! Might be in a very unusual situation where it'd be easier to get a new OSX or Windows recipe going than it would be for Linux until CF shifts toward a newer GCC.

In the meantime, I got the recipe working within the CF Docker image, but using `gcc-7` package from the `QuantStack` channels and uploaded it to my channel on Anaconda.org. This is obviously not a great solution, but it helped me figure out a few new issues when building in the Docker image that'll be good for later. For example, I needed to add `gtk2-devel` to `yum_requirements.txt`,  in order to resolve a few symbols that were in `Qt5Webkit`. The build of QGIS works on our CentOS 6.4 cluster and on my local Arch Linux machine (unlike the previous build I had up on my channel), and Circle CI built my forked branch without me really knowing it would do that ([branch](https://github.com/ceholden/qgis-feedstock/tree/v3.0.0_gcc-7) and [build](https://circleci.com/gh/ceholden/qgis-feedstock/26)).

If anyone is curious, this seemed to work:
`conda create -n qgis3 -c ceholden -c QuantStack qgis=3`

I can probably work a bit this weekend toward the other workaround I had in mind -- patching the QGIS 3 release to work around the compiler bug. I'm getting pretty good at checking in on build failures while I'm doing other stuff, and already have patches for 7 files that get me maybe 2/3rds of the way through the make targets. Not really sure if the edits I'm making will work in practice, but the changes I'm making were suggested in a few bug reports (see [QTBUG-48988](https://bugreports.qt.io/browse/QTBUG-48988) and [QTBUG-53258](https://bugreports.qt.io/browse/QTBUG-53258)).

**Comment by gillins** [comment]
>  I needed to add gtk2-devel to yum_requirements.txt, in order to resolve a few symbols that were in Qt5Webkit

Which symbols were those? `qt` pulls in `glib` (via `gst-plugins-base`) so should link ok, but maybe there is a missing dependency in the `qt` recipe.

**Comment by ceholden** [comment]
@gillins thanks for the suggestion and thoughts.

QGIS's CMake files end up passing `std=gnu++11` (and sets `CMAKE_CXX_STANDARD 11`), and I did try forcing `-std=c++11` specifically by adding it to `CMAKE_CXX_FLAGS`, but I still encountered the "no matching function call for" issue. `gcc 4.8.x` should indeed be fine with the C++11 features, but I guess there's some interaction between `gcc 4.8` and `qt 5.6` that got cleared up when using releases from either project (i.e., since QGIS's repo CI uses `gcc 4.8` with `qt 5.9`). I'm really just guessing here though and would be happy to test anything.

For the other issue, it can't seem to find `XCompositeNameWindowPixmap` and `XCompositeRedirectWindow` that show up in `libQt5WebKit.so.5.6.2`. They're from the `libXcomposite` package, which is installed as part of the requirements for the `gtk2-devel` that listed in the `qt` recipe. Haven't tested but it might get away with just installing `libXcomposite`.

<details>
<summary>Build log that shows the linking error</summary>

``` bash
[2270/4239] Building CXX object src/gui/CMakeFiles/qgis_gui.dir/locator/moc_qgslocatorwidget.cpp.o
[2271/4239] Linking CXX executable output/bin/crssync
FAILED: output/bin/crssync 
: && /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/g++  -DBOOST_MATH_DISABLE_FLOAT128 -m64 -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -O3 -DNDEBUG  -Wl,-rpath,/feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -L/feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib -Wl,--no-undefined   -rdynamic src/crssync/CMakeFiles/crssync.dir/main.cpp.o  -o output/bin/crssync -L/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/build/src/core  -L/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/build/src/gui -Wl,-rpath,/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/build/src/core:/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/build/src/gui:/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/build/output/lib: output/lib/libqgis_core.so.3.0.0 -lproj -lgdal /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Xml.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Svg.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5PrintSupport.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5WebKitWidgets.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Widgets.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5WebKit.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Gui.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Network.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Sql.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Concurrent.so.5.6.2 -lqca-qt5 -lqt5keychain -lproj -lgeos_c -lgdal -lspatialindex -lexpat -lsqlite3 -lspatialite -lzip /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Positioning.so.5.6.2 /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Core.so.5.6.2 && :
/opt/rh/devtoolset-2/root/usr/bin/ld: warning: libXcomposite.so.1, needed by /feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5WebKit.so.5.6.2, not found (try using -rpath or -rpath-link)
/feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5WebKit.so.5.6.2: undefined reference to `XCompositeNameWindowPixmap'
/feedstock_root/build_artefacts/qgis_1521472166607/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5WebKit.so.5.6.2: undefined reference to `XCompositeRedirectWindow'
collect2: error: ld returned 1 exit status
[2272/4239] Building CXX object src/providers/spatialite/qspatialite/CMakeFiles/qsqlspatialite.dir/moc_qsql_spatialite.cpp.o
[2273/4239] Building CXX object src/providers/spatialite/qspatialite/CMakeFiles/qsqlspatialite.dir/qsql_spatialite.cpp.o
[2274/4239] Building CXX object src/providers/gpx/CMakeFiles/gpxprovider.dir/qgsgpxfeatureiterator.cpp.o
[2275/4239] Building CXX object src/providers/gpx/CMakeFiles/gpxprovider.dir/moc_qgsgpxprovider.cpp.o
[2276/4239] Building CXX object src/gui/CMakeFiles/qgis_gui.dir/processing/moc_qgsprocessingalgorithmdialogbase.cpp.o
[2277/4239] Building CXX object src/providers/gpx/CMakeFiles/gpxprovider.dir/qgsgpxprovider.cpp.o
[2278/4239] Building CXX object src/providers/gpx/CMakeFiles/gpxprovider.dir/gpsdata.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/feedstock_root/build_artefacts/qgis_1521472166607/work/qgis-3.0.0/conda_build.sh']' returned non-zero exit status 1.
+ exit 1
```
</details>

**Comment by gillins** [comment]
I had a bit of a look at `qobject.h` line ~293 (which seems to cause the C++11 error) and indeed it has changed in `qt 5.9` - `QtPrivate::QEnableIf` has been replaced with `std::enable_if` which seems to make it work under `gcc 4.8`. Very frustrating. I also played with different compiler flags but no luck...

Sounds a reasonable plan to push on with other platforms until either `gcc` or `qt` is upgraded. I'll have a look at Windows.

Regarding ` XCompositeNameWindowPixmap` that sounds fine - I thought for a moment that `qt` might be pulling in `gtk2` (which may not be installed on the users machine) and that sounded like a bug. I think it is reasonable to expect `libXcomposite` is installed.

**Comment by lpinner** [comment]
Looks like there's some progress on the Qt 5.9 front - https://github.com/conda-forge/qt-feedstock/issues/53#issuecomment-371320162

**Comment by ceholden** [comment]
@gillins thanks for tracking that down. Makes sense to me in hindsight with your explanation but I don't think I would've thought to look like you did.

I'll test out that build of Qt 5.9 from `rdonnelly` channel and see how it goes. That would bring us to differing from the QGIS CI builds by maybe only a patch version, which would be great. Thanks @lpinner!

I was able to test pairing down the yum requirements to just `libXcomposite`, and it worked fine and seems safer than pulling in the entire `gtk2-devel`.

**Comment by SrNetoChan** [comment]
One question. Will it be possible to have two versions of QGIS on the anaconda cloud? There's QGIS 2.18 which is the Long Term Release, and QGIS 3.0 which is the stable branch. If so, how is that done?
Thanks!

**Comment by SrNetoChan** [comment]
BTW, AFAIK QGIS 3.0 packages for linux via ubuntugis are not using Qt5.9. That's the reason why there is no 3D support yet.

**Comment by ceholden** [comment]
@SrNetoChan yes we'll be able to have all past QGIS 2 releases, including future 2.18.* LTR releases, available. This is possible on the Anaconda cloud since the builds are split up by version, but in this feedstock we'll need to keep the recipes separate with Git branches (using the `qgis-2.x` branch once we get a working recipe for QGIS 3).

Our recipe for Qt doesn't include 3D either, but it might be possible to package it up separately down the line.

**Comment by lpinner** [comment]
@ceholden  I've managed to build a QGIS 3.0.1 package that runs on the CentOS 6.9 machine I had trouble with when trying your early test build.  Bit of a kludge, but pulling in gcc 5 and libgcc 5 from the [brown-data-science](https://anaconda.org/brown-data-science/repo) repo did the trick.  Obviously that's not something you want to do for a conda-forge recipe, but it probably confirms the issue with gcc 4.8 (maybe [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56359)???).

I haven't uploaded the package anywhere, I just built and installed it locally.

![image](https://user-images.githubusercontent.com/4827816/39027764-cc5ee21e-4496-11e8-8164-f153944a57e9.png)

**Comment by SrNetoChan** [comment]
@ceholden  So, currently master is building qgis 3.0.2 for windows, hurrey!!

But it seems that Linux is still on qgis 2.18.19. and it only builds with conda2

How can I update it to 2.18.20? It's time to put the qgis-2.x working right?

Do I merge until the last point where 2.18.19 was updated? Is it possible to provide Windows as well there? I would love to help you could give me some pointers.

**Comment by ceholden** [comment]
We finally have builds for Linux/Mac/Windows for QGIS 3.4 :tada:! There's a few caveats right now that I summarized in the PR for the recipe (full gory details in the PR...)

https://github.com/conda-forge/qgis-feedstock/pull/45#issuecomment-477300713
