### ISSUE TITLE
QGIS 3.18 interface does not start in Miniconda with Python 3.9

### ISSUE THREAD

**Issue by felipedantas-pi** [conda-forge/qgis-feedstock#189]
I created a new environment and installed QGIS through the Conda-Forge channel and when trying to open the softwate, it loads the modules, but during Python loading it closed unexpectedly without presenting any error or warning message.

I uninstalled Miniconda and installed it again, only now with the version with Python 3.8 Latest ([LINK](https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe)). I created a new environment again and installed QGIS 3.18 and this time it worked perfectly.

My computer is a Windows 10 Pro for Workstations 64bit

**Comment by ocefpaf** [comment]
Can you add the required debug info for the issue? The results of `conda list` and `conda info` for the failing case.

**Comment by felipedantas-pi** [comment]
`conda list`
Name                    Version                   Build  Channel
boost-cpp                 1.74.0               h54f0996_3    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2020.12.5        py39hcbf5309_1    conda-forge
cffi                      1.14.5           py39h0878f49_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py39hcbf5309_1    conda-forge
coverage                  5.5              py39hb82d6ee_0    conda-forge
cryptography              3.4.7            py39hd8d06c1_0    conda-forge
curl                      7.76.1               h789b8ee_2    conda-forge
exiv2                     0.27.1               hfa2c1cf_0    conda-forge
expat                     2.3.0                h39d44d4_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
future                    0.18.2           py39hcbf5309_3    conda-forge
gdal                      3.2.2            py39h6795fcd_4    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gsl                       2.6                  hdfb1a43_2    conda-forge
hdf4                      4.2.15               h0e5069d_2    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
httplib2                  0.19.1             pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
jinja2                    3.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsoncpp                   1.9.4                h2d74725_2    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
krb5                      1.19.1               hbae68bd_0    conda-forge
laszip                    3.4.3                h6538335_1    conda-forge
laz-perf                  1.4.4                ha925a31_0    conda-forge
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.76.1               h789b8ee_2    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.2.2                hade8cfc_4    conda-forge
libglib                   2.68.2               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1013    conda-forge
liblapack                 3.9.0                     9_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hf689e7d_103    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
libprotobuf               3.16.0               h7755175_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                h763f289_2    conda-forge
libwebp                   1.2.0                h57928b3_0    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
libzip                    1.7.3                hfed4ece_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
markupsafe                2.0.0            py39hb82d6ee_0    conda-forge
mkl                       2021.2.0           hb70f87d_389    conda-forge
mock                      4.0.3            py39hcbf5309_1    conda-forge
nitro                     2.7.dev6             h33f27b4_3    conda-forge
nose2                     0.9.2                      py_0    conda-forge
numpy                     1.20.2           py39h6635163_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
owslib                    0.24.1             pyhd8ed1ab_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pdal                      2.2.0                h56c84bb_7    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
proj                      8.0.0                h1cfcee9_0    conda-forge
psycopg2                  2.8.6            py39h0878f49_3    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py39h1007a03_1    conda-forge
pyqt                      5.12.3           py39hcbf5309_7    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_7    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_7    conda-forge
pyqtchart                 5.12             py39h415ef7b_7    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_7    conda-forge
pyqtwebkit                5.212            py39h8235778_1    conda-forge
pysocks                   1.7.1            py39hcbf5309_3    conda-forge
python                    3.9.4           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39hb82d6ee_0    conda-forge
qca                       2.2.1                hd7ce7fb_3    conda-forge
qgis                      3.18.3           py39hbcfb2ae_0    conda-forge
qjson                     0.9.0             hd7ce7fb_1006    conda-forge
qscintilla2               2.11.2           py39h8235778_4    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtkeychain                0.12.0               h552f0f6_0    conda-forge
qtlocation                5.12.9               ha925a31_0    conda-forge
qtwebkit                  5.212                hb258684_1    conda-forge
qwt                       6.1.6                h552f0f6_0    conda-forge
qwtpolar                  1.1.1                hd7ce7fb_7    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                49.6.0           py39hcbf5309_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h8ffe710_0    conda-forge
tbb                       2021.2.0             h2d74725_0    conda-forge
tiledb                    2.2.9                hf84e3da_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
wincertstore              0.2             py39hcbf5309_1006    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge

`conda info`
active environment : qgis318_py392
active env location : C:\Users\FelipeDantas\miniconda3\envs\qgis318_py392
shell level : 1
user config file : C:\Users\FelipeDantas\.condarc
populated config files : C:\Users\FelipeDantas\.condarc
conda version : 4.9.2
conda-build version : not installed
python version : 3.9.1.final.0
virtual packages : __win=0=0
                           __archspec=1=x86_64
base environment : C:\Users\FelipeDantas\miniconda3  (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                       https://repo.anaconda.com/pkgs/main/noarch
                       https://repo.anaconda.com/pkgs/r/win-64
                       https://repo.anaconda.com/pkgs/r/noarch
                       https://repo.anaconda.com/pkgs/msys2/win-64
                       https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\Users\FelipeDantas\miniconda3\pkgs
                        C:\Users\FelipeDantas\.conda\pkgs
                        C:\Users\FelipeDantas\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\FelipeDantas\miniconda3\envs
                          C:\Users\FelipeDantas\.conda\envs
                          C:\Users\FelipeDantas\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/4.9.2 requests/2.25.0 CPython/3.9.1 Windows/10 Windows/10.0.19041
administrator : False
netrc file : None
offline mode : False

**Comment by SrNetoChan** [comment]
@felipedantas-pi I am closing this one for lack of feedback. Please reopen it if its still a problem for you.
