### ISSUE TITLE
Win/mac?

### ISSUE THREAD

**Issue by msarahan** [conda-forge/qgis-feedstock#19]
I'm attending a school on gerrymandering: https://sites.tufts.edu/gerrymandr/

They want to teach qgis, but they direct people to download it directly.  On mac, this means system python.  Yuck.  Is there a reason why this feedstock is linux-only?  I can tackle builds for at least mac, but wanted your advance warning on any hardships I may encounter.

CC @ocefpaf

**Comment by ocefpaf** [comment]
> I'm attending a school on gerrymandering: https://sites.tufts.edu/gerrymandr/

Cool!

> They want to teach qgis, but they direct people to download it directly.  On mac, this means system python.  Yuck.  Is there a reason why this feedstock is linux-only? I can tackle builds for at least mac, but wanted your advance warning on any hardships I may encounter.

I don't recall the issues we had with OS X, maybe @ceholden does. I just submitted #20 to help us investigate it.

I'll take a look on Windows tomorrow too.

**Comment by ceholden** [comment]
Sounds very cool! There isn't any good reason for not having OS X/Windows builds. I just sadly haven't had the time for OS X and I am very inexperienced on Windows. Would love to have the help!

One potential resource for the OS X build is the Homebrew recipe that OSGEO maintains. https://github.com/OSGeo/homebrew-osgeo4mac

**Comment by ceholden** [comment]
We finally have builds for Mac/Windows for QGIS 3.4 :tada:! There's a few caveats right now that I summarized in the PR for the recipe (full gory details in the PR...)

https://github.com/conda-forge/qgis-feedstock/pull/45#issuecomment-477300713

Hope they're of use going forward at least!
