### ISSUE TITLE
Installing qgis using conda on macOS Sierra

### ISSUE THREAD

**Issue by sukhjitsehra** [conda-forge/qgis-feedstock#21]
I am unable to install the qgis 2.18 using the condo-forge and still getting error
> PackageNotFoundError: Package missing in current osx-64 channels: 
  - qgis

kindly suggest

**Comment by cshewmake2** [comment]
Hello,
I am also having this issue. I noticed on the main page that you have listed a "Disabled" Flag for the OSX build. Any info about when this will be back up?
Thanks

**Comment by ceholden** [comment]
We never got a working recipe going for QGIS2 for Mac/Windows, but we finally have builds for Mac/Windows for QGIS 3.4 :tada:! There's a few caveats right now that I summarized in the PR for the recipe (full gory details in the PR...)

https://github.com/conda-forge/qgis-feedstock/pull/45#issuecomment-477300713
