### ISSUE TITLE
Native M1 conda

### ISSUE THREAD

**Issue by amorfinv** [conda-forge/qgis-feedstock#237]
### Comment:

Hello,

From what I can tell, most dependencies are now available natively in ```osx_arm64``` architecture. The last big holdout was ```pyqt5```. However, that is now available via ```conda-forge``` ([here](https://github.com/conda-forge/qt-main-feedstock)) 

I looked at QGIS dependencies that come via ```conda-forge``` and it seems like only a couple dependencies had some issues. Since the ```conda-forge``` version is at 3.18 perhaps some of these aren't required for latest qgis.

Qt related libraries missing in osx-arm64 via ```conda-forge``` 
- ```pyqt-impl```  - deprecated in Qt5.15?
- ```qtkeychain``` - available with homebrew
- ```qtlocation``` - seems to come with ```qt-main``` 
- ```qtserialport``` - seems to come with ```qt-main```
- ```pyqtwebkit``` and ```qtwebkit```   - can be ignored? use ```pyqtwebengine``` or ```qtwebengine```
- ```qca``` - available with homebrew
- ```qjson``` - available with homebrew
- ```qscintilla2```- available with homebrew
- ```qwtpolar``` - available with homebrew (only big sur) [here](https://formulae.brew.sh/formula/qwtpolar#default)

Other missing libraries in osx-arm64 via ```conda-forge``` 
- ```libtasn1``` - available with homebrew

I am going to attempt to build with these and report any updates. I have never tried before so may take a while.

-Andres

See [response](https://github.com/qgis/QGIS/issues/48531#issuecomment-1125451477) from dev in original issue. I wonder if perhaps I should have more patience and wait for qt6 to be completed.

**Comment by SrNetoChan** [comment]
https://github.com/conda-forge/qgis-feedstock/pull/289 its a work in progress.

**Comment by gillins** [comment]
Closed by #289
