### ISSUE TITLE
Drop qwtpolar dependency

### ISSUE THREAD

**Issue by izahn** [conda-forge/qgis-feedstock#245]
Since version 6.2 qwt includes qwtpolar. The qwtpolar dependency should be dropped.

**Comment by izahn** [comment]
Started working on this in https://github.com/conda-forge/qgis-feedstock/pull/248,  might have to wait until after the `qt-main` migration.

**Comment by gillins** [comment]
See https://github.com/conda-forge/qgis-feedstock/pull/248
