### ISSUE TITLE
Installs fine but won't run

### ISSUE THREAD

**Issue by bhjolly** [conda-forge/qgis-feedstock#25]
Tried installing into a brand new environment by itself but QGIS won't start:

$ conda create -n qgis -c conda-forge qgis
...
$ conda activate qgis
(qgis) $ qgis
Warning: loading of qgis translation failed [/home/jollyb/miniconda3/envs/qgis/share/qgis/i18n//qgis_en_NZ]
Warning: loading of qt translation failed [/opt/anaconda1anaconda2anaconda3/translations/qt_en_NZ]
Warning: Object::connect: No such signal QgsNetworkAccessManager::sslErrors( QNetworkReply *, const QList<QSslError> & )
Warning: QSqlDatabase: QSQLITE driver not loaded
Warning: QSqlDatabase: available drivers: QSPATIALITE
ERROR: Opening of authentication db FAILED
Warning: QSqlQuery::prepare: database not open
WARNING: Auth db query exec() FAILED
qgis: symbol lookup error: /home/jollyb/miniconda3/envs/qgis/bin/../lib/libqgis_core.so.2.18.15: undefined symbol: _ZNK15QNetworkRequest16sslConfigurationEv

**Comment by gillins** [comment]
Hi @bhjolly :smile:. I assume this is fixed in the latest build. Please re-open if not.
