### ISSUE TITLE
QGIS 3.22 availability

### ISSUE THREAD

**Issue by dataspun** [conda-forge/qgis-feedstock#251]
### Comment:

As others have recently noted the current `conda-forge` version of QGIS is 3.18 which is [apparently EOL](https://github.com/qgis/QGIS/issues/49940#issuecomment-1225259604).  What are the prospects of updating to 3.22 LTR in the near term?  Thanks!

**Comment by gillins** [comment]
See this PR: https://github.com/conda-forge/qgis-feedstock/pull/250 - seems we are stuck building it. Any help welcome!

**Comment by dataspun** [comment]
I'm curious what circumstances require conda qgis, versus a regular installation of qgis?  What are the challenges faced in the latter environment?

**Comment by SrNetoChan** [comment]
> I'm curious what circumstances require conda qgis, versus a regular installation of qgis?  What are the challenges faced in the latter environment? 

As far as I understand, conda-forge was using a very dated version of Qt 5.12.

On the other hand, from 3.20 onwards, QGIS requires Qt 5.15 to build. While the regular installers are prepared directly by folks from the QGIS project, in conda-forge we needed to wait for the enormous work to make Qt 5.15 available.

After that, many QGIS dependencies based on Qt also needed to be updated.

Currently, it seems all that is sorted out, but there have been other difficulties.

Meanwhile QGIS kept updating it's versions.

Rest assure that there are folks working really hard to bring back QGIS to conda-forge, but we need to be patient.

**Comment by dataspun** [comment]
I'm actually looking to understand the use case for conda-qgis generally. For instance, what makes the standard install of QGIS challenging for a conda user and vice versa?  Are there use cases where a standard install of QGIS accessed by conda environments is not problematic? Thanks!

**Comment by SrNetoChan** [comment]
Personally, I have too use cases for qgis installation from conda.

1 - Allows me to have two versions of QGIS installed on my linux machines. Normally I use the conda installation for the LTR release.
2 - install qgis along with other packages to use in Python development, I find it convenient to setup dev environment in VS Code.

**Comment by SrNetoChan** [comment]
Oh, another benefit is that using conda, the installation process is exactly the same for all operating systems.

**Comment by gillins** [comment]
Also, the conda-forge `gdal` has more drivers meaning I can open more formats in QGIS....

**Comment by SrNetoChan** [comment]
Really? Even compared with windows installers with some proprietary drivers?

**Comment by gillins** [comment]
> Really? Even compared with windows installers with some proprietary drivers?

Actually, I haven't tried on Windows for a long time - should double check but KEA is one of the main formats I use. I know this is installable as a plugin from osgeo4w, but just works out of the box with conda-forge.

**Comment by SrNetoChan** [comment]
Now you made me read about that format, and your name pops several times :-)

**Comment by SrNetoChan** [comment]
3.22 is no available on conda-forge channel.

**Comment by dataspun** [comment]
Re-reading this comment I see you intended to say **3.22 is _now_ available** which is great news!

**Comment by SrNetoChan** [comment]
> @SrNetoChan re-reading your comment I see you intended to say **3.22 is _now_ available** which is great news!

@dataspun ups... sorry!
