### ISSUE TITLE
Cannot correctly initialize standalone PyQGIS application with Anaconda...

### ISSUE THREAD

**Issue by Felix-neko** [conda-forge/qgis-feedstock#30]
Hi all!

I've tried to use your conda package with QGIS 3.0 for Win64.

I've managed to import qgis python package with environment variable PYTHONPATH=C:/Anaconda3/pkgs/qgis-3.0.0-py36_vc14_0/Library/python , but still don't know what parameters to set in QgsApplication.setPrefixPath to correctly initialize standalone PyQGIS application (just now we cannot add any layers).

Can you tell me, what should i do?

**Comment by gillins** [comment]
This appears to be fixed with the latest build. You need to install `qgis` into a separate environment and activate first it so the appropriate environment gets set.
