### ISSUE TITLE
@SrNetoChan do you know what version of PyQt5-sip that qgis.org uses?

### ISSUE THREAD

**Issue by SrNetoChan** [conda-forge/qgis-feedstock#357]
@SrNetoChan do you know what version of PyQt5-sip that qgis.org uses?

_Originally posted by @gillins in https://github.com/conda-forge/qgis-feedstock/issues/354#issuecomment-1630108420_

@gillins not sure how to find this

**Comment by gillins** [comment]
I think whoever creates the builds for QGIS.org will know this. I suspect it is 12.12.1 (see https://github.com/conda-forge/qgis-feedstock/issues/346#issuecomment-1647297605).

**Comment by gillins** [comment]
Fixed by #358 (well at least we got versions that worked together)
