### ISSUE TITLE
Update recipe to new QGIS LTR v3.4.2

### ISSUE THREAD

**Issue by michaeltryby** [conda-forge/qgis-feedstock#44]
Issue: It would be great if this recipe were updated to the new QGIS LTR v3.4.2.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ceholden** [comment]
Pretty close to merging #45, which should close this issue and make QGIS available on 3 platforms (Mac/Linux/Windows) for the first time with 3.4.5 (or 3.4.6). Going to close this now if you don't mind

**Comment by michaeltryby** [comment]
@ceholden This is fantastic! Thanks so much!

**Comment by ceholden** [comment]
Sorry things too longer than expected, but the builds are up now for QGIS 3.4.6. There's a few minor caveats right now that I wrote up them up in the PR (see the long comment history for more details...)

https://github.com/conda-forge/qgis-feedstock/pull/45#issuecomment-477300713
