### ISSUE TITLE
Recipe for 3.6?

### ISSUE THREAD

**Issue by SrNetoChan** [conda-forge/qgis-feedstock#46]
@ceholden @ocefpaf 

This is not actually an issue. It's more of a question. As you know QGIS has an LTR version (now 3.4), and stable version (3.6). In a month the stable branch will become 3.8, while QGIS 3.4 will the RTL.

Can we keep a recipe for both version, do we need a separate branch in the feedstock, how does that work?

**Comment by ocefpaf** [comment]
The best way to handle that is with branches.

**Comment by SrNetoChan** [comment]
So, we create a branch for let's say LTR and master can be the stable one or vice versa. How do we make conda-forge build the different branches?

**Comment by ocefpaf** [comment]
> So, we create a branch for let's say LTR and master can be the stable

Yep. I can create the branches. BTW, we already have the `qgis-2.x` branch but I guess that master (stable) and LTR (the 3.6 version now) is better.

> How do we make conda-forge build the different branches?

Just send PRs to the branch and they'll build and upload the same as master.

**Comment by ocefpaf** [comment]
Done. See https://github.com/conda-forge/qgis-feedstock/tree/LTR

**Comment by SrNetoChan** [comment]
Thanks. In this case, we can bump master to 3.6.1 and keep the LTR at 3.4.x already provided a PR for that.

**Comment by SrNetoChan** [comment]
If you don't mind I will add myself as a maintainer. I can keep an eye on new releases and update the recipes. If anything gets broken, then I will be blocked :-P
