### ISSUE TITLE
Maybe include <functional> upstream

### ISSUE THREAD

**Issue by elpaso** [conda-forge/qgis-feedstock#47]
https://github.com/conda-forge/qgis-feedstock/blob/0d94ff5f5dc085a5bc5db86408da180d0d70c79a/recipe/patches/0005-include-functional.patch#L19

What platform was it included for?

**Comment by ceholden** [comment]
Would love to get that upstream! Been meaning to submit a few issues/questions now the recipe builds but a little out of steam just now.

The patch is needed to build on Linux (GCC7 - see [transition notes](https://www.gnu.org/software/gcc/gcc-7/porting_to.html)) and was also needed on Windows (Visual Studio 14). It wasn't needed on Mac (Clang 4.0) but I left it applied on this platform anyway

**Comment by elpaso** [comment]
I can build and test on Linux (clang) and windows (MSVC) and I'd be happy to review if you want to make a PR upstream.

**Comment by ceholden** [comment]
Merged upstream and backported to LTR version so we can remove our patch in the next version. Thanks!

**Comment by elpaso** [comment]
@elpaso thank you! Sorry I didn't have time to review but I see other core devs helped :)
