### ISSUE TITLE
Please restart recent builds

### ISSUE THREAD

**Issue by mfansler** [conda-forge/qgis-feedstock#489]
The latest builds after PR merge had timeout failures (possibly CI issues). Would one of the maintainers mind hitting restart on the CI? See here: https://github.com/conda-forge/qgis-feedstock/runs/34293501292

**Comment by ocefpaf** [comment]
Just did. Fingers crossed.

**Comment by gillins** [comment]
Done I think. Reopen this if you are still having trouble...
