### ISSUE TITLE
Missing PyQt5 and Webkit dependencies

### ISSUE THREAD

**Issue by SrNetoChan** [conda-forge/qgis-feedstock#68]
Issue:

When opening QGIS 3.4.8 LTR from conda installation, several plugins complained about missing dependencies, one of the plugins asks the user to install pythos3-pyqt5.qtwebkit

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/aneto/miniconda3/envs/qgis_ltr:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cfitsio                   3.430             h0bd2449_1002    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
coverage                  4.5.3            py37h14c3975_0    conda-forge
cryptography              2.6.1            py37h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
future                    0.17.1                py37_1000    conda-forge
gdal                      2.4.1            py37hf242f0b_3    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.4.0                h37c48d4_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
httplib2                  0.12.3                   py37_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   2.4.1                h02bbc0b_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libspatialindex           1.9.0                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4c5cd43_1028    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
libzip                    1.5.1             h2f06484_1003    conda-forge
lxml                      4.3.3            py37h7ec2d77_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mock                      3.0.5                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nose2                     0.9.1                      py_0    conda-forge
numpy                     1.16.3           py37he5ce36f_0    conda-forge
openblas                  0.3.6                h6e990d7_2    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
owslib                    0.17.1                     py_0    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1                     py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
plotly                    3.9.0                      py_0    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
psycopg2                  2.8.2            py37h72c5cf5_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyproj                    2.1.3            py37hc44880f_2    conda-forge
pyqt                      5.9.2            py37hcca6a23_0    conda-forge
pyrsistent                0.15.2           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
qca                       2.2.1                h279c94e_0    conda-forge
qgis                      3.4.8            py37h758d154_0    conda-forge
qjson                     0.9.0             h279c94e_1005    conda-forge
qscintilla2               2.11.1           py37hd2e5223_2    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
qtkeychain                0.9.1             h279c94e_1001    conda-forge
qtlocation                5.9.7                he1b5a44_0    conda-forge
qtserialport              5.9.8                h279c94e_0    conda-forge
qwt                       6.1.4             h279c94e_1003    conda-forge
qwtpolar                  1.1.1                h279c94e_6    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

    active environment : qgis_ltr
    active env location : /home/aneto/miniconda3/envs/qgis_ltr
            shell level : 1
       user config file : /home/aneto/.condarc
 populated config files : /home/aneto/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/aneto/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aneto/miniconda3/pkgs
                          /home/aneto/.conda/pkgs
       envs directories : /home/aneto/miniconda3/envs
                          /home/aneto/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-48-generic ubuntu/18.04.2 glibc/
2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by gillins** [comment]
@SrNetoChan I think the `qgis` plugin installs are going to be a bit problematic for us. We can't be expected to install dependencies for every possible plugin. One thing we could do is provide conda packages for commonly used plugins and we could then capture the dependencies for each one. Just my 2 cents.

Which plugins are you having trouble with? 

Webkit is being retired in favour of WebEngine (which we do provide) in Qt. Do you know if the problem plugin is considering moving to WebEngine?

BTW we used to have a `qtwebkit` build which we archived when `qgis` itself no longer needed it. See discussion here: https://github.com/conda-forge/qtwebkit-feedstock/pull/9. I guess it would be possible to get this building again - you would also have to modify the `pyqt` build to pick it up - quite a bit of work for one plugin.

**Comment by SrNetoChan** [comment]
Hi @gillins I got problems with several plugins, namely:

- qgis2threejs
- dataplotly
- QGIS Resource sharing
- qgis2web

Disclaimer: I am neither a core developer or a true package manager. Just a QGIS Poweruser, tester and documentarian. Therefore, my comments may not be valid :-)

I agree that we should not care about plugins dependecies, but it seems that those plugins work fine both on normal Ubuntu packaging, and in OSGeo4W packaging. I think QGIS packaging manager are aware of the transition to WebEngine, but decided to keep webkit for a while, waiting for more adoptions from the plugin developers to it.>

Would be nice if "we" could do the same. This  a bit desonest proposal as I have no skills to do it myself :)

**Comment by dakcarto** [comment]
@gillins wrote:
> BTW we used to have a `qtwebkit` build which we archived when `qgis` itself no longer needed it. See discussion here: [conda-forge/qtwebkit-feedstock#9](https://github.com/conda-forge/qtwebkit-feedstock/pull/9). ...

This is not really the case for QGIS:
https://github.com/qgis/QGIS/blob/master/CMakeLists.txt#L335-L341

and some functionality _depends_ upon it (currently checking if this is still true):
http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-qgis2web-and-qtwebkit-tp5378226p5378445.html

Synopsis is:
- QGIS _can_ compile without it, and against just QtWebEngine
- QGIS full functionality is best achieved when using QtWebKit

Towards this end, I have also created a [`pyqtwebit` package](https://github.com/osgeo-forge/pyqtwebkit-feedstock) for adding the bindings just for QtWebKit/QtWebKitWidgets.

I suggest the following steps:
- Unarchive `qtwebkit`
- I can update and submit PR for `pyqtwebit` to conda-forge
- I am willing to help maintain both recipes
- Maintain recipes until EOL for 5.9.x in conda-forge; after which, either QtWebkit can no longer be maintained with latest version > 5.9, or QGIS no longer needs it (or its missing functionality can be lived with).

**Comment by dakcarto** [comment]
Also, I have gotten this [`qtwebkit` package compiling for Windows](https://github.com/osgeo-forge/qtwebkit-feedstock/tree/5.9.0). The `qgis-common` package [setup.hint](https://download.osgeo.org/osgeo4w/x86_64/release/qgis/qgis-common/setup.hint) for OSGeo4W also [depends](https://download.osgeo.org/osgeo4w/x86_64/release/qgis/qgis-common/setup.hint) upon its [`qtwebkit-qt5-libs` package](https://download.osgeo.org/osgeo4w/x86_64/release/qt5/qtwebkit-qt5/qtwebkit-qt5-libs/).

**Comment by nyalldawson** [comment]
@gillins 

> Webkit is being retired in favour of WebEngine (which we do provide) in Qt. Do you know if the problem plugin is considering moving to WebEngine?

Unfortunately webengine is still very limited in the functionality it exposes vs qtwebkit. QGIS (and some plugins) can't port to webengine because the required api just isn't available in webengine.

> BTW we used to have a qtwebkit build which we archived when qgis itself no longer needed it.

QGIS still requires webkit. There's a build-time switch which disables it, but that's just a hack to allow a build to work. The resultant QGIS build will be missing core functionality as a result.

**Comment by gillins** [comment]
I'm happy to for `qtwebkit` to be un-archived if you can get it compiling. I remember that we were having some trouble getting it to build esp. on OSX which made us hopeful it could be retired. Didn't realise that QGIS still needed it...

**Comment by dakcarto** [comment]
@gillins, thanks for the reply. If the `qtwebkit` repo is unarchived, I am willing to try and work out any issues with building on macOS and Windows. Do we need to contact @ocefpaf for this, or can you unarchive the repo yourself?

**Comment by gillins** [comment]
I think @ocefpaf has to do it (well if I can do it I can't work out how)....

**Comment by ocefpaf** [comment]
> @gillins, thanks for the reply. If the `qtwebkit` repo is unarchived, I am willing to try and work out any issues with building on macOS and Windows. Do we need to contact @ocefpaf for this, or can you unarchive the repo yourself?

Done. See https://github.com/conda-forge/qtwebkit-feedstock

> I think @ocefpaf has to do it (well if I can do it I can't work out how)....

Nope. It has to be a core member.

**Comment by gillins** [comment]
Thanks @ocefpaf !

**Comment by gillins** [comment]
@dakcarto any luck getting this working?

**Comment by SrNetoChan** [comment]
Any news about this? Using QGIS without Webkit is a no go for most people.

**Comment by ThomasG77** [comment]
For me too, Qgis from Conda breaks QGIS when using composer. I can't render HTML content from `QgsLayoutItemLabel` when ticking render as HTML and it also fails when I try to use HTML within `QgsLayoutItemHtml` (I'm able to add the component but not to complete the HTML box).
Not including Webkit breaks these QGIS core functionalities (already mentioned by @dakcarto link http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-qgis2web-and-qtwebkit-tp5378226p5378445.html)

PS: although I'm mentioning the component names from a programmer viewpoint, the issues are in the GUI: it freeze everything when I try HTML rendering.

**Comment by gillins** [comment]
@ThomasG77 We need https://github.com/conda-forge/qtwebkit-feedstock building first, but I don't think anyone has had the time. Is this something you could look into?

**Comment by dakcarto** [comment]
Oh wow, I totally forgot about this. Sorry.

I'm doing a custom build of conda-forge's `qt` 5.12 tonight. I might be able to start in on `qtwebkit` as well. However, there is only the [dev source code for 5.12 now](https://github.com/qt/qtwebkit/releases), not [like for 5.9.x](http://download.qt.io/community_releases/5.9/5.9.0-final/). This is what I used for building `qtwebkit` for [Windows a while back](https://github.com/osgeo-forge/qtwebkit-feedstock/blob/5.9.0/recipe/meta.yaml#L12).

**Comment by gillins** [comment]
@dakcarto are we still waiting for a final release of `qtwebkit` 5.12 before doing this? Were you able to get one of the alphas building?

**Comment by ThomasG77** [comment]
You can look at http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/src/submodules/ maybe for 5.12 webkit version?

**Comment by gillins** [comment]
Thanks @ThomasG77 - is this the same as the code in https://github.com/qt/qtwebkit ?

If you think this is what we should be using please submit a PR to https://github.com/conda-forge/qtwebkit-feedstock

**Comment by SrNetoChan** [comment]
Although we were able to build QGIS with QtWebkit, there are still problems finding module PyQt5.QtWebKit.

@gillins @ocefpaf I wonder if PyQt5 feedstock needs to be changed somehow to be built with QtWebKit too.

**Comment by gillins** [comment]
> I wonder if PyQt5 feedstock needs to be changed somehow to be built with QtWebKit too.

Hmm probably. Not sure what is involved in doing this...

**Comment by SrNetoChan** [comment]
@dakcarto hi! Any idea what might be missing? Currently linux and osx builds without problems with QtWebkit, but pyqt5.qtwebkit still can't be found within QGIS

**Comment by dakcarto** [comment]
> @dakcarto hi! Any idea what might be missing? Currently linux and osx builds without problems with QtWebkit, but pyqt5.qtwebkit still can't be found within QGIS

Hi Alexandre! The C++ lib and Python binding module were separate recipes:
https://github.com/osgeo-forge/pyqtwebkit-feedstock

That will need ported as well, or added to the C++ recipe.
