### ISSUE TITLE
Patch can be removed on 3.8.1 release

### ISSUE THREAD

**Issue by dakcarto** [conda-forge/qgis-feedstock#77]
Just a quick note that the following patch can be dropped on next release (v3.8.1):
[patches/0008-mac-dark-theme.patch ](https://github.com/conda-forge/qgis-feedstock/blob/master/recipe/meta.yaml#L27-L28)

I have committed the change to both [release-3_8](https://github.com/qgis/QGIS/pull/30424) and [master](https://github.com/qgis/QGIS/pull/30422) branches.

**Comment by ocefpaf** [comment]
Done in https://github.com/conda-forge/qgis-feedstock/pull/80/commits/bdf323508e068f538af6b36506c730c8b2e052b1
