### ISSUE TITLE
Qgis 2.18 error - Ubuntu

### ISSUE THREAD

**Issue by kylefelipe** [conda-forge/qgis-feedstock#79]
Hi, im trying to install qgis 2.18.19 and miniconda is prompting the follow message.

$ conda install qgis=2.18.18
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - qgis=2.18.18 -> dateutil

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
S.O: Ubuntu 
Conda Version: 4.7.5

**Comment by ocefpaf** [comment]
This is probably related to the removal of `free` from the `defaults` channel.
See https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/

You can install a newer version of `qgis` that does not depend on `free` or you can follow the instructions in the blog post above to re-add free.
