### ISSUE TITLE
Add Qgis 2.18.28

### ISSUE THREAD

**Issue by kylefelipe** [conda-forge/qgis-feedstock#82]
Hi!
Here in company, we still use qgis 2.18, due to some issues with Qgis 3.4/3.8.
It's possible add the last version 2.18.28 to the repository?

**Comment by ocefpaf** [comment]
> It's possible add the last version 2.18.28 to the repository?

Sure. If you send a PR adding it we can create a maintenance branch.
Closing this b/c it is a package request that requires a volunteer to do it. Not really a problem for the current team to address.

**Comment by kylefelipe** [comment]
Have some tutorial to do this??
I want to volunteer.

**Comment by ocefpaf** [comment]
If you are familiar with git/github and qgis build you can start with https://conda-forge.org/docs/maintainer/adding_pkgs.html
