### ISSUE TITLE
Cannot open shared object libspatialindex.so.5

### ISSUE THREAD

**Issue by kylefelipe** [conda-forge/qgis-feedstock#92]
Hi i was updating qgis 3.8.2 to Qgis 3.8.3 yesterday and its prompts the follow issue when i try to init qgis

qgis: error while loading shared libraries: libspatialindex.so.5: cannot open shared object file: No such file or directory

S.O: Debian stretch.
conda --version = conda 4.7.12

**Comment by ocefpaf** [comment]
Can you please add the required debug info, the results of `conda list` and `conda info -a`

**Comment by kylefelipe** [comment]
Sorry....
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.2.0                    py37_0    conda-forge
atk                       2.32.0               haf93ef1_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.0           py37h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
coverage                  4.5.4            py37h516909a_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
exiv2                     0.27.1               had08079_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
future                    0.18.1                   py37_0    conda-forge
gdal                      2.4.2            py37h5f563d9_4    conda-forge
gdk-pixbuf                2.36.12           h7a26e22_1003    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gobject-introspection     1.58.2          py37h5503ade_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
gtk2                      2.24.32              h586f36d_1    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
httplib2                  0.14.0                   py37_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   2.4.2                hbef8c27_4    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.6.2             h303dfb8_1003    conda-forge
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_1    conda-forge
libspatialindex           1.9.2                he1b5a44_0    conda-forge
libspatialite             4.3.0a            he1bb1e1_1029    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            hfc65ed5_1004    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                hee79883_5    conda-forge
libzip                    1.5.1             h1a52d62_1005    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mock                      3.0.5                    py37_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nose2                     0.9.1                      py_0    conda-forge
numpy                     1.17.2           py37h95a1406_0    conda-forge
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
owslib                    0.18.0                     py_0    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
plotly                    4.2.1                      py_0    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_1    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
psycopg2                  2.8.4            py37h72c5cf5_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyproj                    2.2.1            py37hc44880f_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
qca                       2.2.1                h279c94e_2    conda-forge
qgis                      3.8.3            py37hee8cbbe_0    conda-forge
qjson                     0.9.0             h279c94e_1005    conda-forge
qscintilla2               2.11.2           py37h279c94e_0    conda-forge
qt                        5.9.7                h0c104cb_3    conda-forge
qtkeychain                0.9.1             h279c94e_1001    conda-forge
qtlocation                5.9.7                he1b5a44_1    conda-forge
qtserialport              5.9.8                h279c94e_0    conda-forge
qwt                       6.1.4             h279c94e_1003    conda-forge
qwtpolar                  1.1.1                h279c94e_6    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge

conda info -a
     active environment : qgis_lr
    active env location : /home/kylefelipe/miniconda3/envs/qgis_lr
            shell level : 1
       user config file : /home/kylefelipe/.condarc
 populated config files : /home/kylefelipe/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /home/kylefelipe/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kylefelipe/miniconda3/pkgs
                          /home/kylefelipe/.conda/pkgs
       envs directories : /home/kylefelipe/miniconda3/envs
                          /home/kylefelipe/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/2.7.16 Linux/4.9.0-11-amd64 debian/9.11 glibc/2.24
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /home/kylefelipe/miniconda3
chattelegram             /home/kylefelipe/miniconda3/envs/chattelegram
geo_pandas               /home/kylefelipe/miniconda3/envs/geo_pandas
imagem                   /home/kylefelipe/miniconda3/envs/imagem
qgis_218                 /home/kylefelipe/miniconda3/envs/qgis_218
qgis_34                  /home/kylefelipe/miniconda3/envs/qgis_34
qgis_lr               *  /home/kylefelipe/miniconda3/envs/qgis_lr
qgis_test                /home/kylefelipe/miniconda3/envs/qgis_test

sys.version: 2.7.16 |Anaconda, Inc.| (default, Mar 14...
sys.prefix: /home/kylefelipe/miniconda3
sys.executable: /home/kylefelipe/miniconda3/bin/python
conda location: /home/kylefelipe/miniconda3/lib/python2.7/site-packages/conda
conda-build: None
conda-env: /home/kylefelipe/miniconda3/bin/conda-env
conda-server: /home/kylefelipe/miniconda3/bin/conda-server
user site dirs: ~/.local/lib/python3.5
                ~/.local/lib/python3.6
                ~/.local/lib/python3.7
                ~/.local/lib/python2.7

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: qgis_lr
CONDA_EXE: /home/kylefelipe/miniconda3/bin/conda
CONDA_PREFIX: /home/kylefelipe/miniconda3/envs/qgis_lr
CONDA_PROMPT_MODIFIER: (qgis_lr) 
CONDA_PYTHON_EXE: /home/kylefelipe/miniconda3/bin/python
CONDA_ROOT: /home/kylefelipe/miniconda3
CONDA_SHLVL: 1
PATH: /home/kylefelipe/miniconda3/bin:/home/kylefelipe/miniconda3/envs/qgis_lr/bin:/home/kylefelipe/miniconda3/bin:/home/kylefelipe/miniconda3/condabin:/home/kylefelipe/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PYTHONPATH: /home/kylefelipe/miniconda3/envs/qgis_lr/share/qgis/python/plugins:/home/kylefelipe/miniconda3/envs/qgis_lr/share/qgis/python:
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
WINDOWPATH: 2

**Comment by ThomasG77** [comment]
I had to cheat e.g

```
ln -s /home/thomasg/miniconda3/lib/libspatialindex.so.6 /home/thomasg/miniconda3/lib/libspatialindex.so.5
```
You need to adapt path depending of your conda environment

How I found out?
Run `updatedb` then `locate libspatialindex.so` You should find a `libspatialindex.so.6` but no `libspatialindex.so.5`. I've choose to go the dirty way (symlinking...)

**Comment by ocefpaf** [comment]
Looks like the soname changed in the latest `libspatialindex` version and we need to pin it. @ThomasG77, your solution is OK and newer builds of `qgis` will also pick the new `libspatialindex`, but we need to fix this "for good" in `conda-forge`. Working on it...

**Comment by ocefpaf** [comment]
Long term fix in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/315
